### PR TITLE
Do not set watches on SMBFS filesystems. 

### PR DESCRIPTION
**Pull request by arrowd**
This is a workaround for [PR 243836](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243836). I plan to open a PR to fix the core issue in SMBFS, too.

The behavior can be overridden with INOTIFY_FORCE_WATCH_SMBFS env var.

### CODE REVIEW

**Comment by wulf7** [comment]
It looks like you are trying to reimplement feature which is already existing. Try to rebuild libinotify with following option specified at configure stage: --enable-skip-subfiles=nfs,fusefs,smbfs

**Comment by arrowd** [comment]
Not only it works, it also still report some changes for SMBFS mount!

Can I enable `--enable-skip-subfiles=smbfs` by default in `devel/libinotify` port?

**Comment by wulf7** [comment]
> Can I enable `--enable-skip-subfiles=smbfs` by default in `devel/libinotify` port?

I do not know. I do not maintain it

**Comment by wulf7** [comment]
I recommend to add fusefs to this list too. Opening directory with e.g. photos triggers full directory content download on mtpfs which is painfully slow

**Pull request closed without merging**
